name: prefs_todo_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dev: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.2

dev_dependencies:
  custom_lint: ^0.6.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1
  riverpod_lint: ^2.3.9
flutter:
  uses-material-design: true
